// Bundles the endless-glory.vercel.app auth-only Vercel functions (api/CLAUDE.md).
// Vercel's Node runtime transpiles api/*.ts per-file without bundling node_modules,
// which breaks on firebase-admin's dependency chain (jwks-rsa requires the ESM-only
// jose package via require(), which only works when a bundler resolves it at build
// time). Mirrors scripts/build_server.mjs's esbuild approach: bundle:true inlines
// every dependency into one self-contained file per function, sidestepping that
// CJS/ESM interop failure entirely. Source lives under api/_src/ (not auto-routed by
// Vercel, whose convention skips any path with a leading underscore); this step emits
// the actual routed files (api/register.js, api/login.js, api/auth/firebase.js),
// gitignored build output, regenerated by `npm run build` (never hand-edit them).
import * as esbuild from 'esbuild';

const ENTRIES = [
  { entry: 'api/_src/register.ts', outfile: 'api/register.js' },
  { entry: 'api/_src/login.ts', outfile: 'api/login.js' },
  { entry: 'api/_src/auth/firebase.ts', outfile: 'api/auth/firebase.js' },
];

for (const { entry, outfile } of ENTRIES) {
  await esbuild.build({
    entryPoints: [entry],
    bundle: true,
    platform: 'node',
    format: 'esm',
    external: ['pg-native'],
    outfile,
  });
}

console.log(`[build:api] bundled ${ENTRIES.length} Vercel auth function(s)`);
